name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0
  # google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/vectors/group_4_x2.svg
  - assets/vectors/biqr_code_scan_23_x2.svg
  - assets/vectors/nimbusqr_code_1_x2.svg
  - assets/images/rectangle_3.png
  - assets/vectors/biqr_code_scan_3_x2.svg
  - assets/vectors/icon_9_x2.svg
  - assets/vectors/intersect_221_x2.svg
  - assets/vectors/icon_6_x2.svg
  - assets/vectors/biqr_code_scan_5_x2.svg
  - assets/vectors/intersect_x2.svg
  - assets/vectors/icon_8_x2.svg
  - assets/vectors/icon_2_x2.svg
  - assets/vectors/biqr_code_scan_11_x2.svg
  - assets/vectors/icon_1_x2.svg
  - assets/vectors/biqr_code_scan_33_x2.svg
  - assets/vectors/biqr_code_scan_38_x2.svg
  - assets/vectors/intersect_2_x2.svg
  - assets/vectors/biqr_code_scan_24_x2.svg
  - assets/vectors/icon_3_x2.svg
  - assets/vectors/icon_5_x2.svg
  - assets/vectors/intersect_22_x2.svg
  - assets/vectors/biqr_code_scan_40_x2.svg
  - assets/vectors/icon_4_x2.svg
  - assets/vectors/icon_10_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/biqr_code_scan_10_x2.svg
  - assets/vectors/biqr_code_scan_18_x2.svg
  - assets/vectors/icon_x2.svg
  - assets/vectors/biqr_code_scan_29_x2.svg
  - assets/vectors/icon_7_x2.svg
  - assets/vectors/biqr_code_scan_1_x2.svg
  - assets/vectors/union_x2.svg
  - assets/vectors/intersect_1_x2.svg
  - assets/images/rectangle_5.jpeg
  - assets/vectors/container_7_x2.svg
  - assets/vectors/vector_119_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/vector_159_x2.svg
  - assets/vectors/vector_197_x2.svg
  - assets/vectors/biqr_code_scan_8_x2.svg
  - assets/vectors/vector_102_x2.svg
  - assets/vectors/group_3_x2.svg
  - assets/vectors/arcticonsqrforkeepass_x2.svg
  - assets/vectors/biqr_code_scan_4_x2.svg
  - assets/images/icons_8_twitter_1001.png
  - assets/images/icons_8_location_1001.png
  - assets/images/icons_8_internet_1001.png
  - assets/images/icons_8_contacts_1001.png
  - assets/images/icons_8_call_1001.png
  - assets/images/icons_8_wi_fi_1001.png
  - assets/images/icons_8_calendar_1001.png
  - assets/images/icons_8_organization_1001.png
  - assets/images/icons_8_instagram_1001.png
  - assets/images/icons_8_whatsapp_1001.png
  - assets/images/icons_8_auto_rotate_based_on_text_1001.png
  - assets/images/icons_8_secured_letter_1001.png
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/vector_99_x2.svg
  - assets/vectors/vector_196_x2.svg
  - assets/vectors/biqr_code_scan_34_x2.svg
  - assets/vectors/vector_173_x2.svg
  - assets/vectors/biqr_code_scan_12_x2.svg
  - assets/vectors/vector_200_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/vector_218_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/vectors/vector_108_x2.svg
  - assets/vectors/biqr_code_scan_32_x2.svg
  - assets/vectors/biqr_code_scan_28_x2.svg
  - assets/vectors/vector_81_x2.svg
  - assets/vectors/vector_91_x2.svg
  - assets/vectors/vector_206_x2.svg
  - assets/vectors/vector_136_x2.svg
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/vector_180_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/biqr_code_scan_14_x2.svg
  - assets/vectors/vector_163_x2.svg
  - assets/vectors/vector_224_x2.svg
  - assets/vectors/vector_92_x2.svg
  - assets/vectors/vector_192_x2.svg
  - assets/vectors/vector_167_x2.svg
  - assets/vectors/vector_181_x2.svg
  - assets/vectors/vector_75_x2.svg
  - assets/vectors/vector_186_x2.svg
  - assets/vectors/vector_169_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/vector_154_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/vectors/vector_243_x2.svg
  - assets/vectors/vector_188_x2.svg
  - assets/vectors/vector_219_x2.svg
  - assets/vectors/vector_225_x2.svg
  - assets/vectors/vector_223_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_201_x2.svg
  - assets/vectors/biqr_code_scan_2_x2.svg
  - assets/vectors/vector_238_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_127_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/vector_246_x2.svg
  - assets/vectors/vector_175_x2.svg
  - assets/vectors/vector_211_x2.svg
  - assets/vectors/vector_204_x2.svg
  - assets/vectors/vector_172_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_212_x2.svg
  - assets/vectors/vector_174_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/vector_151_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/vector_89_x2.svg
  - assets/vectors/vector_130_x2.svg
  - assets/vectors/vector_126_x2.svg
  - assets/vectors/vector_228_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/vector_93_x2.svg
  - assets/vectors/vector_95_x2.svg
  - assets/vectors/vector_140_x2.svg
  - assets/vectors/vector_191_x2.svg
  - assets/vectors/vector_118_x2.svg
  - assets/vectors/vector_144_x2.svg
  - assets/vectors/vector_183_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/vector_166_x2.svg
  - assets/vectors/vector_189_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_131_x2.svg
  - assets/vectors/vector_190_x2.svg
  - assets/vectors/vector_236_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/vector_209_x2.svg
  - assets/vectors/vector_103_x2.svg
  - assets/vectors/vector_141_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/vector_213_x2.svg
  - assets/vectors/vector_184_x2.svg
  - assets/vectors/vector_230_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/vectors/vector_120_x2.svg
  - assets/vectors/vector_203_x2.svg
  - assets/vectors/vector_207_x2.svg
  - assets/vectors/vector_182_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/vector_86_x2.svg
  - assets/vectors/vector_220_x2.svg
  - assets/vectors/vector_104_x2.svg
  - assets/vectors/vector_176_x2.svg
  - assets/vectors/vector_121_x2.svg
  - assets/vectors/vector_112_x2.svg
  - assets/vectors/vector_185_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/vectors/vector_109_x2.svg
  - assets/vectors/vector_227_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_249_x2.svg
  - assets/vectors/vector_199_x2.svg
  - assets/vectors/vector_98_x2.svg
  - assets/vectors/vector_105_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/vector_82_x2.svg
  - assets/vectors/vector_165_x2.svg
  - assets/vectors/vector_142_x2.svg
  - assets/vectors/vector_84_x2.svg
  - assets/vectors/vector_146_x2.svg
  - assets/vectors/vector_123_x2.svg
  - assets/vectors/vector_110_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/vector_178_x2.svg
  - assets/vectors/vector_234_x2.svg
  - assets/vectors/biqr_code_scan_16_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/vector_160_x2.svg
  - assets/vectors/vector_152_x2.svg
  - assets/vectors/biqr_code_scan_35_x2.svg
  - assets/vectors/vector_148_x2.svg
  - assets/vectors/vector_237_x2.svg
  - assets/vectors/vector_244_x2.svg
  - assets/vectors/vector_215_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_241_x2.svg
  - assets/vectors/vector_87_x2.svg
  - assets/vectors/vector_114_x2.svg
  - assets/vectors/vector_96_x2.svg
  - assets/vectors/vector_231_x2.svg
  - assets/vectors/vector_233_x2.svg
  - assets/vectors/vector_64_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/vector_107_x2.svg
  - assets/vectors/biqr_code_scan_17_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_125_x2.svg
  - assets/vectors/vector_83_x2.svg
  - assets/vectors/vector_239_x2.svg
  - assets/vectors/vector_117_x2.svg
  - assets/vectors/vector_187_x2.svg
  - assets/vectors/vector_133_x2.svg
  - assets/vectors/biqr_code_scan_20_x2.svg
  - assets/vectors/vector_235_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/vector_242_x2.svg
  - assets/vectors/biqr_code_scan_39_x2.svg
  - assets/vectors/vector_248_x2.svg
  - assets/vectors/vector_210_x2.svg
  - assets/vectors/vector_94_x2.svg
  - assets/vectors/biqr_code_scan_21_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_132_x2.svg
  - assets/vectors/vector_100_x2.svg
  - assets/vectors/vector_162_x2.svg
  - assets/vectors/vector_149_x2.svg
  - assets/vectors/vector_135_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_90_x2.svg
  - assets/vectors/vector_145_x2.svg
  - assets/vectors/vector_229_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_111_x2.svg
  - assets/vectors/biqr_code_scan_31_x2.svg
  - assets/vectors/vector_240_x2.svg
  - assets/images/rectangle_5.jpeg
  - assets/vectors/container_6_x2.svg
  - assets/vectors/clarityimage_gallery_solid_4_x2.svg
  - assets/vectors/exclude_3_x2.svg
  - assets/vectors/exclude_x2.svg
  - assets/vectors/vector_156_x2.svg
  - assets/vectors/group_365_x2.svg
  - assets/vectors/clarityimage_gallery_solid_5_x2.svg
  - assets/vectors/vector_193_x2.svg
  - assets/vectors/exclude_4_x2.svg
  - assets/vectors/group_36_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/vector_205_x2.svg
  - assets/vectors/biqr_code_scan_36_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/vector_134_x2.svg
  - assets/vectors/biqr_code_scan_9_x2.svg
  - assets/vectors/vector_170_x2.svg
  - assets/vectors/biqr_code_scan_25_x2.svg
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/vector_122_x2.svg
  - assets/vectors/exclude_1_x2.svg
  - assets/vectors/biqr_code_scan_x2.svg
  - assets/vectors/vector_214_x2.svg
  - assets/vectors/vector_222_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/vector_195_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/vector_137_x2.svg
  - assets/vectors/subtract_1_x2.svg
  - assets/vectors/group_364_x2.svg
  - assets/vectors/vector_198_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/clarityimage_gallery_solid_1_x2.svg
  - assets/vectors/group_362_x2.svg
  - assets/vectors/biqr_code_scan_22_x2.svg
  - assets/vectors/vector_139_x2.svg
  - assets/vectors/container_4_x2.svg
  - assets/vectors/exclude_5_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/biqr_code_scan_26_x2.svg
  - assets/vectors/group_363_x2.svg
  - assets/vectors/clarityimage_gallery_solid_2_x2.svg
  - assets/vectors/container_5_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/clarityimage_gallery_solid_x2.svg
  - assets/vectors/exclude_2_x2.svg
  - assets/vectors/container_3_x2.svg
  - assets/vectors/vector_78_x2.svg
  - assets/vectors/container_2_x2.svg
  - assets/vectors/subtract_x2.svg
  - assets/vectors/vector_147_x2.svg
  - assets/vectors/clarityimage_gallery_solid_3_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/group_361_x2.svg
  - assets/images/screenshot_301110.jpeg
  - assets/images/screenshot_30117.jpeg
  - assets/images/figma.png
  - assets/images/screenshot_30111.jpeg
  - assets/images/screenshot_30118.jpeg
  - assets/images/screenshot_30119.jpeg
  - assets/images/screenshot_30116.jpeg
  - assets/images/rectangle.png
  - assets/images/screenshot_30113.jpeg
  - assets/images/screenshot_301111.jpeg
  - assets/images/screenshot_30114.jpeg
  - assets/images/screenshot_3011.jpeg
  - assets/images/screenshot_30112.jpeg
  - assets/images/screenshot_30115.jpeg
  - assets/vectors/container_8_x2.svg
  - assets/images/group_121.png
  - assets/vectors/vector_85_x2.svg
  - assets/vectors/biqr_code_scan_37_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/vector_76_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/group_78610_x2.svg
  - assets/vectors/vector_115_x2.svg
  - assets/vectors/nimbusqr_code_x2.svg
  - assets/vectors/group_6_x2.svg
  - assets/vectors/biqr_code_scan_7_x2.svg
  - assets/vectors/group_2_x2.svg
  - assets/vectors/biqr_code_scan_19_x2.svg
  - assets/vectors/biqr_code_scan_41_x2.svg
  - assets/vectors/biqr_code_scan_30_x2.svg
  - assets/images/group_121.png
  - assets/vectors/vector_80_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/vector_245_x2.svg
  - assets/vectors/vector_202_x2.svg
  - assets/vectors/vector_208_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/biqr_code_scan_15_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/vector_101_x2.svg
  - assets/vectors/vector_164_x2.svg
  - assets/vectors/vector_158_x2.svg
  - assets/vectors/biqr_code_scan_6_x2.svg
  - assets/vectors/vector_247_x2.svg
  - assets/vectors/vector_113_x2.svg
  - assets/vectors/vector_168_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/vector_106_x2.svg
  - assets/vectors/vector_155_x2.svg
  - assets/vectors/vector_88_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/group_7862_x2.svg
  - assets/vectors/group_78612_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/vector_138_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_226_x2.svg
  - assets/vectors/group_7861_x2.svg
  - assets/vectors/vector_153_x2.svg
  - assets/vectors/vector_161_x2.svg
  - assets/vectors/group_7867_x2.svg
  - assets/vectors/vector_79_x2.svg
  - assets/vectors/vector_171_x2.svg
  - assets/vectors/vector_232_x2.svg
  - assets/vectors/vector_179_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/vector_217_x2.svg
  - assets/vectors/vector_157_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/group_7869_x2.svg
  - assets/vectors/group_7865_x2.svg
  - assets/vectors/group_7864_x2.svg
  - assets/vectors/group_786_x2.svg
  - assets/vectors/group_7866_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/group_78611_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/vector_77_x2.svg
  - assets/vectors/group_7863_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/vector_221_x2.svg
  - assets/vectors/vector_97_x2.svg
  - assets/vectors/group_7868_x2.svg
  - assets/vectors/vector_116_x2.svg
  - assets/vectors/bounds_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/vector_124_x2.svg
  - assets/vectors/vector_143_x2.svg
  - assets/vectors/bounds_4_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/vector_150_x2.svg
  - assets/vectors/group_x2.svg
  - assets/vectors/vector_129_x2.svg
  - assets/vectors/bounds_7_x2.svg
  - assets/vectors/group_5_x2.svg
  - assets/vectors/vector_177_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/vector_216_x2.svg
  - assets/vectors/vector_68_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/vector_128_x2.svg
  - assets/vectors/vector_194_x2.svg
  - assets/vectors/bounds_2_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/bounds_6_x2.svg
  - assets/vectors/bounds_5_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/biqr_code_scan_27_x2.svg
  - assets/vectors/biqr_code_scan_13_x2.svg

